{% set version = "4.59" %}

package:
  name: pyro4
  version: {{ version }}

source:
  fn: Pyro4-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pyro4/Pyro4-{{ version }}.tar.gz
  sha256: 6a39dadbd2a83b6fd5ab7f5402f8a4befd467b5c0404b8610a8797f748b72a38

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pyro4-ns = Pyro4.naming:main
    - pyro4-nsc = Pyro4.nsc:main
    - pyro4-test-echoserver = Pyro4.test.echoserver:main
    - pyro4-check-config = Pyro4.configuration:configuration_dump
    - pyro4-flameserver = Pyro4.utils.flameserver:main
    - pyro4-httpgateway = Pyro4.utils.httpgateway:main

requirements:
  build:
    - python
    - setuptools
    - serpent >=1.19

  run:
    - python
    - serpent >=1.19

test:
  imports:
    - Pyro4
    - Pyro4.socketserver
    - Pyro4.test
    - Pyro4.utils

  commands:
    - pyro4-ns --help
    - pyro4-nsc --help
    - pyro4-test-echoserver --help
    - pyro4-check-config --help
    - pyro4-flameserver --help
    - pyro4-httpgateway --help

about:
  home: http://pythonhosted.org/Pyro4/
  license: MIT
  summary: 'Distributed object middleware for Python (RPC)'

extra:
  recipe-maintainers:
    - whart222
    - irmen
    - Juanlu001
