{% set version = "4.80" %}

package:
  name: pyro4
  version: {{ version }}

source:
  fn: Pyro4-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pyro4/Pyro4-{{ version }}.tar.gz
  sha256: 46847ca703de3f483fbd0b2d22622f36eff03e6ef7ec7704d4ecaa3964cb2220

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyro4-ns = Pyro4.naming:main
    - pyro4-nsc = Pyro4.nsc:main
    - pyro4-test-echoserver = Pyro4.test.echoserver:main
    - pyro4-check-config = Pyro4.configuration:main
    - pyro4-flameserver = Pyro4.utils.flameserver:main
    - pyro4-httpgateway = Pyro4.utils.httpgateway:main

requirements:
  host:
    - pip
    - python>=2.7
    - setuptools
    - serpent >=1.27

  run:
    - python>=2.7
    - serpent >=1.27

test:
  imports:
    - Pyro4
    - Pyro4.socketserver
    - Pyro4.test
    - Pyro4.utils

  commands:
    - pyro4-ns --help
    - pyro4-nsc --help
    - pyro4-test-echoserver --help
    - pyro4-check-config --help
    - pyro4-flameserver --help
    - pyro4-httpgateway --help

about:
  home: https://pyro4.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: Distributed object middleware for Python (RPC)

extra:
  recipe-maintainers:
    - whart222
    - irmen
