travis:
  secure:
    BINSTAR_TOKEN: XCJSFuh/I9Wi6C7M1LSY25RHPx9xydHQLP//U1jUl+S+MPK2f7Po1cXcT6hSa24VBQ9p/ZESmjI1kSwFZUPsndgS9NwP4soaxzsqbdu9UchUaDCku7kJYgcBbIvtrZwYWp9WFgKbFT8dCJuVAYo3rj2Qk7ZCZsawSC7NAG/qfbwbqTAHuhGE+nUUO4/TQ/LN1sePd4pxUSwAqgnROOvrZ03BvWjdTSXCKwgf+ejm/TrJ1Da6s9GB6BkOOwXqCMGMwiV1Fx8KwYZz7kp1Ykeuqd/FKQvL65vxb3fFGVn3vXG6YAk1x2BethGS+xsQ409Svq4ZUc7VMvV5i+oHIWAmkbJ39SqM61jQsGMISFScUR4BTl1Rw3nKoqBQCMIOxXygAplGfIfuLOSg+FMsDnNmeduKtzpWQ5A/V8uuXiv47E+CzKTeVoDpWAUFnA470U3gK3baZfHYXrnzaIzFlpR+hkW0eECAvKjYODX46tTMYBh/+O8wpHfX7pZN3v9r7QelVRsHosRJQpMOY3WsDtOqKV4w5VOcNQCwgZnCltbTs1d8mMHms/Ig/1h3eE4n4Df9CINXMzRx4Mg7LroM5zUhkjID3aUvRY7ArGDj1tRviEf53pMbTBMIT3kn3OVYi7eemWHZ/An3VtWvpIZ7j/MYgiA9k5erWuOagZCjEt0Sf0I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
