travis:
  secure:
    BINSTAR_TOKEN: dv5etkURnYuXk2Au5lQ9zMy5zO2ZxacDnNa2SMTfJgrYpz40sC/OMSbjeUZNyFF1BCF3KD6GkiMhoxYb43rJk1VRFyDO/ETo7E/V7njxbjatgwCbf5zUuS42dcefg03ar61BvclEA/+KWsFlV6s59w9GSvr7BjmiMXM6ggQLjMIGAQlc3O1lFnNP6AhNB+7GlV1+3Bvh+iFDwnv5n4id2Wdy/90rk2r9HAMhP+wrKU8jMKBhZnUMsOLtdc5clShL6lFLJCdTrVi2e145Nj8TU74IY1nWurhK4O0pvJwjEgjImCvixOTJGFlN3VGSgkGKmSyO/4Jd1yzYoSCNBGxzN307vSm95150rtOOR6BP09nnL/ADZ+QhxM6kXQs4jHAQXCgJQ3Xjmq3gjcUd4jgoTmKGqyDP7/vfkQWyXC8nQdvAull75yMZ/sZc+RFuZTieBb99WaRX2cXo56GeVyhZK16kHlMEzbf0MNvhtEBG7vDnT0QYB7hsBidhK4ynt4FFm8K7Aqd366QpFwCUhmxwsvJc1rkW9Lx3CHIuEj3XBE8kcN17KbJxUPSXS5AhaEhnhmxajNQng1IrPeZ4D9ilVUbP6WUklcHNJ1v3hrUM+phPjfjC3G8Ac9L1mnzAzpHcpyDSav2Xc6t9tQPApHHDERNpZukf8aGpMKFngdbh/4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
