travis:
  secure:
    BINSTAR_TOKEN: aCBZ7UxHL0RWLNa2EG5FyOXgXKLpFpf+SLscYo7IvuxjV8XDUP2w1wz2Vs7HHmxFnpSSVuLuhArMHrcxWxzyzLJxUfdZq/DzMFhTbd2fuKiqA9aUYKkGGuKPsrcruKHweGVDRNrAAHKG5rXM70E3cuzQHE5RxAG/KLBbb5mwCzryEmW4vngCxwmnUnr214kpTXShWtjaTdqfBaoqDMuvFhj1rGKnPmPQPi6tuPfnd0KbtiNCB5mlZbrBv6RhBIWnMOX6o9bK4l1Efs5H0LKmqvtR3itP+aMEdqgpo9tbbBSWTwIUpWNkS0pzVVt2xzmaDEsKdabYq0PBwrYiFU5+EflGBHEyXZWhNdvsdSqx6oYxiB1DW0EcjgP+FredIkTpmWrsrbIf0utHrT4K+U5kUeSTh2HLrSelzYh3v/OAz4g7eaICQYdjD4+TcGxhwA7/kiESBnLJcgBCEOHe4iUv0rLYh0OvvxligYYwwxZDdpi9J+ge4tH4Q9RIBssMJHNCTEj30nsSann+LXPwdKoL9jqa0NbpKpIDw9DmFl3g9PXGV4CCD0F7Sd/qnHHp5KsOQ8ad0t15ug8FxnNTr63y4GI9G+hJV+n92Ss3lokgBPpvyOTkeABv8RJYJINFfAXmzI9eyLnm+qUDKjnkS4Y/MK4KrwkvSbUPBn9zLDlQG/U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
