travis:
  secure:
    BINSTAR_TOKEN: TtgN5QvkTEBB+C2c7tfkGwCTQ8SP+Hp5CQv3q1b7MhVFxpdYrfFCWnY0mCW1dEta+DDUMOtXJWM13ky/6qMFjlb6DoZp2m0P/IQN6frO/d6Ng2YfpaMA8NOSwcwffB3MVMJ8PnHqshzcNerIDb1ir0LoF61rgKO9zEc2DLxU4k/Fj62AM0JjqqAjW9xOb0SlR3PDJz9rHDaTjrWQ5Uujf4kEcqcTNp7soj0jw4N7yNgqLl3ZvmQ6UQSymJ+JwnMdJndeMNniw6ytu/4SONlBFIvYlRHUG9k6Eqb4iXdBHDrd3fGxdCVgWVAFHpgPqGt9t6de3DE0CBXT6iXVlyJTJvdRZjlVp8q5h+JBSsA2HQgvnUGR5h0XdJovRFCui4GaCXjJqLYkUOsRfblL6EO3I7OTaEODOlx/NRVrnd38O+Y6mWMyxMXDR1ti1xWbZwoHCRQNBY56TY2EZ3OKoTs83JR3D/Bv4K1tRmBYplB0XWK1ETq5CmBpVgiV94Xvl5HhdxIhV3eLQJpzeYYbUmwCFzVcepr9lN84cSZOaSPi9yzRMI7Z06m850zbaXFp7PsIQAx2lqsHhZVm/MEwOoK12RreRWuy1cRb6NjwVVFlU8hFZd7wKKZF16TuX699BwACFTNvSrA/QwZRhgO229MRkYbniAynjt5IdjuqEY/xoBE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
