travis:
  secure:
    BINSTAR_TOKEN: LC6Y4+kVSKNuTNXOZIHxcy/yTqTLNEpgIwI5YjWW6ltLKkorJQd1eKnRaxp+C8zoVJzchv145dObdHaCSArnWiNgIm3ZLveQg7rLoCy8LBOQTnX0c/8V1zL6rSk7aw/vxUzHRa9+jrigdPw77Ldlys+kvWLHrkQaYaUhZOtbRjFnJRFPTcwku8wxNd8iYMGXRjC6RaX+/5vFo2CgOgs92TZkRwXOXxe7V/nUBzYBi3cXlAP6uqc8EZYAPEmjGVuk89i0iSY/HSVsuVTZhJ6ZowlX71eNEVHg5AL9+D9boY9acVtnf05bkkHVjl9BmauBy6hBLumC+ZeTpD/2wejp+SfwpdxAF91yHHroN9sBdMcQq2Jo2g8VSlVBBJSuZZfxa9MQInopZJEawBayRC/R2Z8NcZVLu7smj63IeGJTKo1vV9UcQIBNLOaj9xj4ZOOkiMClfCz/tBwQgOUIGtYsscLxmOJvILSfSLu5y1LrJX8GkVwv8dpoOxNYCp69zDfQXF1fuDLzOh6xCFxBXKv4c30hC6izAywsTH8Oz9i30iCIVfLHF7Igj7CubN7k0nOTv46MuWoIqqgXJqff9CMaj5qNaqrmPCIjUwFGKBAx11Rfif9zRLovnRxTlTf2mygVqqQG9En03y2AXI1ODq5BmmjFKJqj3ivrapY00QvtNGI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
